<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Task $task) {

        $em = $this->getEntityManager();
        $em->beginTransaction();
        $em->persist($task);
        $em->flush();
        $em->commit();

    }

    public function merge(Task $task) {

        $em = $this->getEntityManager();
        $em->beginTransaction();
        $em->merge($task);
        $em->flush();
        $em->commit();

    }

    public function remove(Task $task) {
        $em = $this->getEntityManager();
        $em->beginTransaction();
        $em->remove($task);
        $em->flush();
        $em->commit();
    }
}
